sudo: required
services:
        - docker


before_install:
        - docker build -t navdeep0/docker-react  -f Dockerfile.dev .
script:
        - docker run -e CI=true navdeep0/docker-react npm run test        
                
